### ISSUE TITLE
Pawn when black go first

### ISSUE THREAD

**Issue by seekkii** [ctabin/jchess#35]
Hello, do you think it is a good idea to subclass pawnDisplacementRule and Pawn and override direction inside pawnDisplaymentRule so you have 2 new classes that you can use when black go first ? Because i believe currently the pawn only moves in direction for white.

**Comment by ctabin** [comment]
Hi @seekkii,

Not sure about what you want to do, but as you can see [here](https://github.com/ctabin/jchess/blob/master/src/main/java/ch/astorm/jchess/core/rules/PawnDisplacementRule.java#L21) the direction is adjusted depending on the color, so BLACK pawns are going down.

**Comment by corlaez** [comment]
I think this means that he want's to set a custom board and let black pieces go first. Not sure if the lib supports that currently.
An use case I can think of is to set up a particular board and tell the person to find a check mate in two turns (using black pieces).

**Comment by ctabin** [comment]
Mmmmh but then one can simple use [this](https://github.com/ctabin/jchess#color-on-move) :thinking:

**Comment by corlaez** [comment]
oh ok it is clear we support that, I don't know. OP should clarify

**Comment by corlaez** [comment]
@seekkii in my opinion that's a matter of presentation rather than changing the direction pawns are supposed to go towards.
You would just like to take jchess entities as a model and then when you translate it into a image (by console logging, html generation or whatever) make sure you print the elements in such a way that black is shown in the other side of the board.

There are a couple of renderer classes to print a board here (such as UnicodePositionRenderer). You can create your own renderer as a client of the library, those are just two renderers that are offered out of the box.

**Comment by corlaez** [comment]
If you already made the changes, do you have a link to them to take a look?

If I have to take a guess it seems that your renderer pretends whites are blacks and blacks are whites but still renders in the usual order. That would indeed affect the movements (because white tower is excepted in a1 not the black tower). Is this what you did?

But I do have a solution for that, it's what I suggested initially. A new renderer that ensures the board is printed backwards, you don´t pretend blacks are whites and whites are black you just display A1 on the top right instead of the usual bottom left. That, I believe should solve the issue.

**Comment by corlaez** [comment]
You keep implying that a1 should always be the bottom left square (whether blacks are on the bottom or not). I am convinced this is not the case. Whether blacks are on top, bottom, sideways, their towers are row 8 and whites are row 1.

Maybe you *should* rewrite your input handler if it cannot handle the fact that the bottom row is actually row 8th when blacks are displayed on the bottom

**Comment by ctabin** [comment]
I've added a parameter to the `ASCIIPositionRenderer` to define the orientation for the board presentation.
